### ISSUE TITLE
TCP ControlPort socket

### ISSUE THREAD

**Issue by djkazic** [guardianproject/tor-android#104]
I see that this library migrated from a TCP controlPort to a file / UNIX socket. Is there any way to get the former functionality back so you can point applications that only support TCP controlPorts at it?

**Comment by n8fr8** [comment]
I agree we should provide it as an option. 

That said, it isn't that hard to switch - see how we use the file socket approach in Orbot here:
https://github.com/guardianproject/orbot/blob/master/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java#L824

//moved torService to a local variable, since we only need it once
TorService torService = ((TorService.LocalBinder) iBinder).getService();
conn = torService.getTorControlConnection()
conn.addRawEventListener(mOrbotRawEventListener);

                        logNotice(getString(R.string.log_notice_connected_to_tor_control_port));

                        //now set our own events
                        ArrayList<String> events = new ArrayList<>(Arrays.asList(TorControlCommands.EVENT_OR_CONN_STATUS,
                                TorControlCommands.EVENT_CIRCUIT_STATUS, TorControlCommands.EVENT_NOTICE_MSG,
                                TorControlCommands.EVENT_WARN_MSG, TorControlCommands.EVENT_ERR_MSG,
                                TorControlCommands.EVENT_BANDWIDTH_USED, TorControlCommands.EVENT_NEW_DESC,
                                TorControlCommands.EVENT_ADDRMAP));
                        if (Prefs.useDebugLogging()) {
                            events.add(TorControlCommands.EVENT_DEBUG_MSG);
                            events.add(TorControlCommands.EVENT_INFO_MSG);
                        }

                        if (Prefs.useDebugLogging() || Prefs.showExpandedNotifications())
                            events.add(TorControlCommands.EVENT_STREAM_STATUS);

                        conn.setEvents(events);

**Comment by djkazic** [comment]
I ended up using torrc like Orbot does to set the options I needed. Thanks for the pointer in the right direction.

**Comment by n8fr8** [comment]
Fantastic!
