### ISSUE TITLE
tor.so missing from nativeLibraryDir when app is installed through app bundle with non-debuggable config.

### ISSUE THREAD

**Issue by kukabi** [guardianproject/tor-android#28]
`tor.so` does not exist in the native library folder when the depending Android app is installed through an app bundle prepared with a config with setting `debuggable false`. `AndroidManifest.xml` has the property `android:extractNativeLibs="true"`. Issue happens with either debug or release config with the property `debuggable false`. It causes `TorNativeLoader` to fail with message `Unable to find file in apk:lib/armeabi-v7a/tor`.

`ABI` splitting is enabled by default, but I explicitly enable it with:

```
bundle {
  abi {
    enableSplit = true
  }
}
```

`gradle.properties` also has the property `android.bundle.enableUncompressedNativeLibs=false`.

**Comment by CjS77** [comment]
Unfortunately, debuggable must be false:

> You uploaded a debuggable APK or Android App Bundle. For security reasons you need to disable debugging before it can be published in Google Play. Find out more about debuggable APKs or Android App Bundles.

**Comment by kukabi** [comment]
It runs fine when I set:
```
bundle {
  abi {
    enableSplit = false
  }
}
```

**Comment by kukabi** [comment]
Android in non-debuggable mode ignores any native binaries that don't follow the `lib{name}.so` format, so `tor.so` file gets ignored and it cannot be found in the native binaries folder.

**Comment by hsjoberg** [comment]
Any update on this one? It pretty much makes `tor-android` non-usable when targeting Android SDK 29.

**Comment by 05nelsonm** [comment]
Try adding to your app module's `android` block

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

They should be automatically extracted from your apk to your application's nativeDir where executables are safe to execute from for API 29+.

@n8fr8 , if this is still an issue, might we sync up with projects (see https://github.com/05nelsonm/TOPL-Android-TorBinary)?

**Comment by hsjoberg** [comment]
@05nelsonm Thanks for your reply.
I tried to run the test project (sampletorapp) in `android-tor` and got it to work.
However, I don't want to change my project just to make Tor work.

Upon further investigation I saw that the tor.so -> libtor.so issue was actually fixed by @eighthave in https://github.com/guardianproject/tor-android/pull/21.
The fix is included in `org.torproject:tor-android-binary:0.4.2.7a`.

Unfortunately updating `tor-android-binary` will still not work if you're relying on [`Tor_Onion_Proxy_Library`](https://github.com/thaliproject/Tor_Onion_Proxy_Library) as it has `tor.so` instead of `libtor.so` hardcoded in [AndroidTorConfig](https://github.com/thaliproject/Tor_Onion_Proxy_Library/blob/15217297a6bac9b16fffa4d965ead96e87a22701/android/src/main/java/com/msopentech/thali/android/toronionproxy/AndroidTorConfig.java#L37) and [TorConfig](https://github.com/thaliproject/Tor_Onion_Proxy_Library/blob/15217297a6bac9b16fffa4d965ead96e87a22701/universal/src/main/java/com/msopentech/thali/toronionproxy/TorConfig.java#L448).

I'll have fork and a PR up to Tor_Onion_Proxy_Library up soon, but to get it work on SDK 29 regardless of bundling options, update tor.so to libtor.so in Tor_Onion_Proxy_Library and use `org.torproject:tor-android-binary:0.4.2.7a`

**Comment by 05nelsonm** [comment]
You could just use the universal module's tor config class and use the builder to configure things yourself.

TOPL's android module has a plethora of issues, which are able to be side stepped by relying on the universal module instead.

You may be interested, too, in my fork of TOPL which fixes most of those issues. https://topl-android.matthewnelson.io

**Comment by kukabi** [comment]
@hsjoberg our current solution is to just copy the `libtor.so` binaries from the [latest Orbot universal release](https://github.com/guardianproject/orbot/releases/download/16.3.0-RC-1-tor-0.4.2.7/Orbot-16.3.0-RC-1-tor-0.4.2.7-fullperm-universal-release.apk) from the [Orbot releases page](https://github.com/guardianproject/orbot/releases).

Unpack the `apk` file (it's actually a zip file, you may change the extension to `zip` and uzip), you'll find the binaries for different architectures under `lib`. Copy the desired architecture folders into `src/main/jniLibs` and, voila. You can also find the OBFS4 proxy binary `libobfs4proxy.so` in that `lib` folder.

This solution may look a bit hacky, but it works. I've also tested the OBFS4 proxy, that works too.

**Comment by hsjoberg** [comment]
@05nelsonm Wow your TOPL-fork looks really good! It looks much more Android-like in that it uses an Android service and is written in Kotlin. I've tried it out and it works great.

I'm really considering supporting your fork because the state of the official project is not very pretty.
But I'm hesitant to use it because of the change from Apache license to GPL3.  😕

One feature request would be the ability to disable and not requiring a notification (showstopper for me).
Also AFAICT there's no way to set the Control port through .

> You could just use the universal module's tor config class and use the builder to configure things yourself.

Thank you, I'll take a look.

> @hsjoberg our current solution is to just copy the libtor.so binaries from the latest Orbot universal release from the Orbot releases page.
Thank you @kukabi, that should probably work yes.

**Comment by 05nelsonm** [comment]
There is a bit that'll be changing with publicly available APIs of the `topl-core` module which is why it's not advertised in the documentation, but you can substitute the `topl-service` dependency with `topl-core` and do your own thing.

Yep, good ol' GPL3.

**Comment by eighthave** [comment]
I'm currently working on a new official release process for the pluggable transport libraries.  They will be shipped as AAR libs on Maven Central.  I tried to get them easily reproducible, but there are a couple bugs in _gomobile_ preventing that: https://github.com/golang/go/issues/40254

Then there is the same goal for the new _TorService_, which currently lives in my fork.  Work is underway, albeit slowly, to move Orbot and Tor Browser to that _TorService_.  https://gitlab.com/eighthave/tor-android

**Comment by eighthave** [comment]
you can also find the new _TorService_ in a pull request here: https://github.com/guardianproject/tor-android/pull/31

**Comment by 05nelsonm** [comment]
Is there a way to separate out the binaries from the service such that only binaries are provided via the dependency, and the optional service can be imported separately?

**Comment by eighthave** [comment]
with this new TorService approach, the libtor.so binaries would be
pretty much useless without the _TorService.java_.  It is only the steps
required to start/stop and attach jtorctl.  This replaces running it as
a UNIX daemon and makes it a native Android _Service_.  It is not
possible to have a native Android _TorService_ without a Java file.

**Comment by 05nelsonm** [comment]
Agreed, but providing only the binaries separately allows other implementations flexibility in starting a `Process` using the binaries from the app's native directory to execute instead of loading the native lib, if they don't wish to utilize the native Android _Service_.

There are many bugs in earlier versions of Android with using `System.loadLibrary("tor")`, which is why Relinker was created. See https://medium.com/keepsafe-engineering/relinker-v1-2-is-here-b8f1799e22fe

Providing only the binaries as a separate module that can be depended on by a module containing the _TorService.java_ required for native execution would allow for others to do as they desire with the binaries w/o having the extra code, while still maintaining a SSOT for the binaries being executed in their application if they do not wish to use the native service for the aforementioned reasons pertaining to bugs with lesser APIs.

**Comment by goapunk** [comment]
Just as a side note: over at briarproject.org we publish our tor binaries at jcenter: https://bintray.com/briarproject/org.briarproject

**Comment by hsjoberg** [comment]
Both the TorService for [`tor-android`](https://github.com/guardianproject/tor-android/pull/31) and [TorOnionProxyLibrary-Android](https://topl-android.matthewnelson.io/) library looks promising,  
but to solve the current situation regarding tor.so -> libtor.so for those who use Tor_Onion_Proxy_Library, I've opened a PR [here](https://github.com/thaliproject/Tor_Onion_Proxy_Library/pull/152).

**Comment by eighthave** [comment]
It is clear that the Android security team is working to remove support for running UNIX daemons, on iOS this is already the case.  I consider running Tor as a daemon (e.g. its own process) to be deprecated on Android.  I'm working with the core tor team to make sure we make tor act as a first class Android _Service_, and I also believe this should be the only supported method for running Tor on Android.  A UNIX analogy would be supporting running daemons that don't declare a `main()` function.  Sure its possible, but it requires custom code that is brittle and works against the operating system.  Of course, its free software, and people hack whatever they want.  Going forward, supporting Tor as a UNIX daemon on Android wastes very limited developer time, IMHO.  For example, this native service with shared library approach means we can share more code between Android and iOS.

@hsjoberg brings up a perfect example: the native Android Service works fine as an Uncompressed Native Lib.  The UNIX daemon approach requires `android.bundle.enableUncompressedNativeLibs=false`.

**Comment by eighthave** [comment]
obsoleted by #31

**Comment by eighthave** [comment]
going forward, we will publish our binaries on Maven Central https://repo1.maven.org/maven2/info/guardianproject/tor-android
